import React from 'react';
import { MapPinned, Sparkles, Plane, TrainFront, MapPin, CalendarDays, ArrowUpRight, Clock3, Star, Wallet, Heart, Navigation, RotateCcw, Hotel, CircleAlert, LoaderCircle, LocateFixed, X, BookmarkCheck } from 'lucide-react';
import TripMap from '../TripMap.jsx';
import { Pill, SectionHeading } from '../components/Primitives.jsx';
import { dateLabel, money, timeOnly } from '../format.mjs';

export default function PlanView({ form, actions, plan, placeCount, selectedDay, message, memory, detailOnly = false }) {
  const { query, destination, originCity, days, startDate, location, locationState, loading } = form;
  const { updateQuery, setDestination, setStartDate, setDays, generate, detectLocation, setOriginCity, updateMemory, setMessage, rememberTrip, setSelectedDay } = actions;
  const bestFlight = plan?.flights?.find(flight => !flight.redEye);
  const bestTrain = plan?.trains?.find(train => !train.redEye);
  return <>
          {!detailOnly ? <section className="hero">
            <div className="hero-copy"><Pill icon={Sparkles} className="hero-pill">更懂你的旅行 Agent</Pill><h1>下一站，<em>去发现新的。</em></h1><p>说出你想去的地方。我们结合你的出发位置、偏好和过往足迹，安排一段真正属于你的旅程。</p></div>
            <div className="hero-art" aria-hidden="true"><div className="sun" /><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="hero-plane"><Plane size={32} fill="currentColor" /></div><div className="hero-pin"><MapPin size={22} fill="currentColor" /></div><div className="hero-caption">A NEW ROUTE<br />AWAITS YOU ↗</div></div>
          </section> : null}

          {!detailOnly ? <section className="composer" aria-label="创建旅行计划">
            <div className="composer-top"><div className="composer-icon"><Sparkles size={18} /></div><strong>想去哪里走走？</strong><span>自然语言规划</span></div>
            <textarea value={query} onChange={event => updateQuery(event.target.value)} placeholder="例如：我想去深圳玩 3 天，坐飞机，票价优先但不要红眼航班…" rows={2} />
            <div className="composer-controls">
              <label><MapPin size={16} /><span>目的地</span><input aria-label="目的地" value={destination} onChange={event => setDestination(event.target.value)} /></label>
              <label><CalendarDays size={16} /><span>出发日期</span><input aria-label="出发日期" type="date" value={startDate} onChange={event => setStartDate(event.target.value)} /></label>
              <label><Clock3 size={16} /><span>天数</span><select aria-label="旅行天数" value={days} onChange={event => setDays(Number(event.target.value))}>{[1, 2, 3, 4, 5, 6, 7].map(value => <option key={value} value={value}>{value} 天</option>)}</select></label>
              <button type="button" className="primary-button" onClick={generate} disabled={loading}>{loading ? <LoaderCircle size={18} className="spin" /> : <Sparkles size={18} />}{loading ? '正在规划' : '生成行程'}</button>
            </div>
          </section> : null}
          {!detailOnly ? <div className="origin-strip"><div><LocateFixed size={18} /><button type="button" onClick={detectLocation}>{locationState}</button>{location ? <small>{location.lat.toFixed(3)}, {location.lng.toFixed(3)}</small> : null}</div><label>或手动输入出发城市 <input aria-label="出发城市" value={originCity} onChange={event => { setOriginCity(event.target.value); updateMemory({ homeCity: event.target.value }); }} placeholder="如：上海" /></label></div> : null}
          {message ? <div className="feedback" role="status"><CircleAlert size={16} />{message}<button type="button" onClick={() => setMessage('')} aria-label="关闭消息"><X size={15} /></button></div> : null}

          <section className="overview"><div><div className="eyebrow">YOUR NEXT JOURNEY</div><h2>{plan.destination}<span> / {plan.days} 天的全新探索</span></h2><p>{plan.intro}</p><div className="overview-pills"><Pill icon={CalendarDays}>{dateLabel(plan.startDate)} — {dateLabel(plan.endDate)}</Pill><Pill icon={MapPin}>{placeCount} 个地点</Pill><Pill icon={RotateCcw}>{plan.revisit ? '再次探索 · 已排除到访地点' : '初次探索'}</Pill></div></div><div className="overview-number"><strong>{String(plan.days).padStart(2, '0')}</strong><span>DAYS<br />AWAY</span></div></section>

          <div className="two-column">
            <section className="transport-section card-surface"><SectionHeading eyebrow="01 · GETTING THERE" title="怎么去，才符合你的节奏" note={plan.originCity ? `从 ${plan.originCity} 出发 · ${plan.transportPreference === 'flight' ? '优先飞机，价格优先且避开红眼' : '优先高铁'}` : '请定位或填写出发城市，以查询真实交通方案。'} />
              {bestFlight ? <div className="flight-card"><div className="flight-card-head"><Pill icon={Plane}>符合偏好</Pill><span>实时查询 · {bestFlight.provider}</span></div><div className="flight-times"><div><strong>{timeOnly(bestFlight.departureAt)}</strong><small>{bestFlight.origin}</small></div><div className="flight-path"><Plane size={18} /><span /></div><div><strong>{timeOnly(bestFlight.arrivalAt)}</strong><small>{bestFlight.destination}</small></div><b>{bestFlight.totalPrice === null ? '价格待查' : money(bestFlight.totalPrice, bestFlight.currency)}</b></div><div className="flight-meta">{bestFlight.airline} {bestFlight.flightNumber} · {bestFlight.stops ? `${bestFlight.stops} 次中转` : '直飞'} · {bestFlight.priceBasis || '报价条件待核'} · 最终价格以预订时验价为准 {bestFlight.bookingUrl ? <a href={bestFlight.bookingUrl} target="_blank" rel="noreferrer">查看供应商 <ArrowUpRight size={14} /></a> : null}</div></div> : <div className="empty-offer"><span className="empty-offer-icon"><Plane size={22} /></span><div><strong>白天航班 · 低价优先</strong><p>{plan.originCity ? '已记录你的偏好。本次没有取得可核实的航班报价。' : '填写出发城市后可确定机场与交通方案。'}</p></div><span className="pending-badge">暂无实时报价</span></div>}
              <div className="transport-secondary"><TrainFront size={19} /><div><strong>{bestTrain ? `${bestTrain.trainNumber || '火车'} · ${timeOnly(bestTrain.departureAt)} → ${timeOnly(bestTrain.arrivalAt)}` : '高铁作为备选'}</strong><small>{bestTrain ? `${bestTrain.provider} · ${bestTrain.origin || '出发站'} → ${bestTrain.destination || '到达站'} · ${bestTrain.priceBasis || '参考价'}` : '本次没有取得可核实的火车票报价'}</small></div><span>{bestTrain ? bestTrain.totalPrice === null ? '价格待查' : money(bestTrain.totalPrice, bestTrain.currency) : '待查询'}</span>{bestTrain?.bookingUrl ? <a href={bestTrain.bookingUrl} target="_blank" rel="noreferrer" aria-label="查看火车票供应商页面"><ArrowUpRight size={16} /></a> : null}</div>
            </section>

            <section className="stay-section card-surface"><SectionHeading eyebrow="02 · WHERE TO STAY" title="住在行程的中心" note="结合游玩地点、品牌偏好与每晚预算选择住宿区域。" />
              <div className="stay-area"><div className="stay-area-icon"><Hotel size={22} /></div><div><span>建议住宿区域</span><strong>{plan.stayArea?.name || `${plan.destination}市区`}</strong><p>{plan.stayArea?.note || '酒店数据源接入后，可结合行程计算适合的住宿位置。'}</p></div></div>
              <div className="stay-preference"><div><Heart size={15} />偏好品牌：{plan.hotelBrands?.join('、') || '未设置'}</div><div><Wallet size={15} />每晚预算：{money(memory.hotelNightBudget)}</div></div>
              {plan.hotels?.length ? <div className="hotel-offers">{plan.hotels.slice(0, 3).map(hotel => <div className="hotel-offer" key={hotel.id}><div><strong>{hotel.name}</strong><small>{hotel.provider} · {hotel.address || '地址待核实'}</small></div><span>{hotel.displayPrice ? `${money(hotel.displayPrice, hotel.currency)} · ${hotel.priceBasis}` : '价格待核实'}</span>{hotel.bookingUrl ? <a href={hotel.bookingUrl} target="_blank" rel="noreferrer" aria-label={`查看 ${hotel.name}`}><ArrowUpRight size={16} /></a> : null}</div>)}</div> : <div className="stay-placeholder">酒店实时库存未连接，当前建议基于地点分布，未虚构房价。</div>}
            </section>
          </div>

          <div className="journey-grid"><section className="itinerary-section"><SectionHeading eyebrow="03 · THE ITINERARY" title="让每一天都有新发现" note={plan.skippedPlaces?.length ? `已避开你去过的：${plan.skippedPlaces.join('、')}` : '同一区域优先串联，减少路上折返。'} action={<button type="button" className="text-button" onClick={rememberTrip}><BookmarkCheck size={17} /> 完成后记住这趟旅程</button>} />
            <div className="day-list">{plan.itinerary?.map(day => <article className="day-card" key={day.day}><div className="day-heading"><span>DAY {String(day.day).padStart(2, '0')}</span><div><strong>{day.title}</strong><small>{dateLabel(day.date)}</small></div><button type="button" onClick={() => setSelectedDay(selectedDay === day.day ? null : day.day)} aria-label={`在地图查看第 ${day.day} 天`}><MapPinned size={17} /></button></div><div className="stop-list">{day.stops.length ? day.stops.map((stop, index) => <div className="stop" key={stop.id}><div className="stop-time">{stop.start}</div><div className="stop-rail"><span />{index < day.stops.length - 1 ? <i /> : null}</div><div className="stop-body"><div className="stop-title"><strong>{stop.name}</strong><span>{stop.category}</span></div><p>{stop.description}</p><div className="stop-meta"><span><Clock3 size={13} /> 游玩约 {stop.duration} 分钟</span>{stop.travelMinutes ? <span><Navigation size={13} /> 路程约 {stop.travelMinutes} 分钟 · {stop.travelSource}</span> : null}{stop.rating ? <span><Star size={13} /> {stop.rating} · {stop.ratingSource}</span> : <span>暂无可信评分</span>}</div></div></div>) : <div className="empty-day">{day.title === '抵达与入住' ? '抵达时间较晚，留给进城和入住，不再安排景点。' : '还没有可核实的新地点，请接入地点源后重新规划。'}</div>}</div></article>)}</div>
            {plan.attractionOffers?.length ? <div className="hotel-offers">{plan.attractionOffers.map((offer, index) => <div className="hotel-offer" key={`${offer.provider}-${offer.placeId}-${index}`}><div><strong>{offer.name} · {offer.productName || '景区详情'}</strong><small>{offer.provider} · {offer.startingPrice ? `起价对应 ${offer.priceDate || '未知日期'}，出游日价格待核` : offer.priceDate ? `标注日期 ${offer.priceDate}` : '日期请到供应商页面核实'}</small></div><span>{offer.price === null ? '价格请到平台查看' : `${money(offer.price, offer.currency)}${offer.startingPrice ? '起' : ''}`}</span>{offer.bookingUrl ? <a href={offer.bookingUrl} target="_blank" rel="noreferrer" aria-label={`查看 ${offer.name} 门票`}><ArrowUpRight size={16} /></a> : null}</div>)}</div> : null}
          </section><aside className="map-column"><div className="map-sticky"><div className="map-title"><div><span>路线地图</span><strong>{plan.destination} · {placeCount} 站</strong></div><MapPinned size={19} /></div><TripMap itinerary={plan.itinerary} selectedDay={selectedDay} onSelectDay={setSelectedDay} /><div className="map-note"><Navigation size={16} /> 地图连线表示地点顺序；每段交通时间以旁边标注的来源为准。</div><div className="map-footer"><span className="map-legend" /><span>按天查看行程</span><span className="map-updated">更新于 {new Date(plan.generatedAt).toLocaleDateString('zh-CN')}</span></div></div></aside></div>
        </>;
}
