import React from 'react';
import { ArrowUpRight, BookmarkCheck, MapPinned, Plane, TrainFront } from 'lucide-react';
import TripMap from '../TripMap.jsx';
import { money, timeOnly } from '../format.mjs';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

function TransportTable({ plan }) {
  const rows = [
    ...(plan.flights || []).map(item => ({ ...item, type: '航班', direction: '去程' })),
    ...(plan.returnFlights || []).map(item => ({ ...item, type: '航班', direction: '返程' })),
    ...(plan.trains || []).map(item => ({ ...item, type: '火车', direction: '去程' })),
    ...(plan.returnTrains || []).map(item => ({ ...item, type: '火车', direction: '返程' })),
  ];
  const selected = rows.filter(item => [plan.recommendedOutboundFlightId, plan.recommendedReturnFlightId, plan.recommendedOutboundTrainId, plan.recommendedReturnTrainId].includes(item.id));
  const visible = [...selected, ...rows.filter(item => !selected.includes(item))].slice(0, 20);
  return <Card><CardHeader><CardTitle>交通候选</CardTitle><CardDescription>真实供应商返回的航班和火车票；仅将有数字价格的候选用于价格排序。</CardDescription></CardHeader><CardContent>{visible.length ? <Table><TableHeader><TableRow><TableHead>类型</TableHead><TableHead>出发 → 抵达</TableHead><TableHead>供应商</TableHead><TableHead>价格</TableHead><TableHead>结果</TableHead></TableRow></TableHeader><TableBody>{visible.map(item => <TableRow key={`${item.type}-${item.direction}-${item.id}`}><TableCell><div className="flex items-center gap-2">{item.type === '航班' ? <Plane /> : <TrainFront />}<span>{item.direction}{item.type}</span></div></TableCell><TableCell className="whitespace-nowrap">{timeOnly(item.departureAt)} → {timeOnly(item.arrivalAt)}</TableCell><TableCell>{item.provider}</TableCell><TableCell>{Number.isFinite(item.totalPrice) ? money(item.totalPrice, item.currency) : '价格未知'}</TableCell><TableCell>{selected.includes(item) ? <Badge>推荐</Badge> : item.bookingUrl ? <a className="inline-flex items-center gap-1 text-primary underline" href={item.bookingUrl} target="_blank" rel="noreferrer">供应商 <ArrowUpRight /></a> : <span className="text-muted-foreground">待验价</span>}</TableCell></TableRow>)}</TableBody></Table> : <p className="text-sm text-muted-foreground">本次没有可核实的航班或火车结果。</p>}</CardContent></Card>;
}

export default function PlanView({ plan, selectedDay, memory, actions }) {
  const placeCount = plan.itinerary.reduce((sum, day) => sum + day.stops.length, 0);
  return <div className="flex flex-col gap-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold tracking-[.16em] text-primary">GENERATED ITINERARY</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{plan.originCity || '出发地待定'} → {plan.destination}</h1><p className="mt-2 text-sm text-muted-foreground">{plan.startDate} 起 · {plan.days} 天 · {placeCount} 个地点 · {plan.agentRun?.status === 'completed' ? 'Step Plan 模型完成' : '规则补全'}</p></div><Button variant="outline" onClick={actions.rememberTrip}><BookmarkCheck data-icon="inline-start" />完成后记住这趟旅程</Button></div>
    <TransportTable plan={plan} />
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="flex min-w-0 flex-col gap-4"><h2 className="text-xl font-semibold">逐日行程</h2>{plan.itinerary.map(day => <Card key={day.day} size="sm"><CardHeader><CardTitle>第 {day.day} 天 · {day.title}</CardTitle><CardDescription>{day.date}</CardDescription><CardAction><Button variant="ghost" size="icon-sm" aria-label={`在地图查看第${day.day}天`} onClick={() => actions.setSelectedDay(selectedDay === day.day ? null : day.day)}><MapPinned /></Button></CardAction></CardHeader><CardContent>{day.stops.length ? <div className="flex flex-col gap-3">{day.stops.map(stop => <div key={stop.id} className="grid grid-cols-[48px_1fr] gap-3 border-t pt-3 first:border-t-0 first:pt-0"><span className="font-mono text-xs text-primary">{stop.start}</span><div><p className="font-medium">{stop.name} <Badge variant="secondary" className="ml-2">{stop.category}</Badge></p><p className="mt-1 text-xs text-muted-foreground">游玩约 {stop.duration} 分钟 · 交通 {stop.travelMinutes || 0} 分钟 · {stop.travelSource || '本段无需转场'}</p></div></div>)}</div> : <p className="text-sm text-muted-foreground">抵达与入住，未安排未经核实的景点。</p>}</CardContent></Card>)}</div><div className="flex flex-col gap-4"><Card><CardHeader><CardTitle>路线地图</CardTitle><CardDescription>连线只表示地点顺序，不代表导航路线。</CardDescription></CardHeader><CardContent><TripMap itinerary={plan.itinerary} selectedDay={selectedDay} onSelectDay={actions.setSelectedDay} /></CardContent></Card><Card><CardHeader><CardTitle>住宿</CardTitle><CardDescription>建议区域：{plan.stayArea?.name || '尚未确定'} · 每晚预算 {money(memory.hotelNightBudget)}</CardDescription></CardHeader><CardContent>{plan.hotels?.length ? <div className="flex flex-col gap-2">{plan.hotels.slice(0, 4).map(hotel => <div key={hotel.id} className="flex justify-between gap-3 border-t pt-2 text-sm"><span>{hotel.name}</span><span>{hotel.displayPrice ? money(hotel.displayPrice, hotel.currency) : '价格待核'}</span></div>)}</div> : <p className="text-sm text-muted-foreground">本次未取得酒店报价；区域建议来自行程地点分布。</p>}</CardContent></Card></div></div>
    <div className="grid gap-6 md:grid-cols-2"><Card><CardHeader><CardTitle>景点产品</CardTitle><CardDescription>门票以对应日期和供应商信息为准。</CardDescription></CardHeader><CardContent>{plan.attractionOffers?.length ? plan.attractionOffers.map((offer, index) => <div key={`${offer.placeId}-${index}`} className="border-t py-2 text-sm first:border-t-0">{offer.name} · {offer.productName} <span className="text-muted-foreground">{offer.provider} · {offer.price == null ? '价格未知' : money(offer.price, offer.currency)}</span></div>) : <p className="text-sm text-muted-foreground">本次未取得可核实的景区产品。</p>}</CardContent></Card><Card><CardHeader><CardTitle>餐饮与地面交通</CardTitle><CardDescription>只展示来源明确的餐饮和路线。</CardDescription></CardHeader><CardContent><p className="text-sm">餐饮 {plan.dining?.length || 0} 条 · 核实路线 {plan.groundJourneys?.length || 0} 段</p><p className="mt-2 text-xs text-muted-foreground">没有高德路线时，行程中的转场时间仅为估算。</p></CardContent></Card></div>
  </div>;
}
