import React from 'react';
import { BookmarkCheck, MapPinned, TrainFront } from 'lucide-react';
import TripMap from '../TripMap.jsx';
import FlightResults from './FlightResults.jsx';
import { money, timeOnly } from '../format.mjs';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

function TransportTable({ plan }) {
  const rows = [
    ...(plan.trains || []).map(item => ({ ...item, type: '火车', direction: '去程' })),
    ...(plan.returnTrains || []).map(item => ({ ...item, type: '火车', direction: '返程' })),
  ];
  const selected = rows.filter(item => [plan.recommendedOutboundFlightId, plan.recommendedReturnFlightId, plan.recommendedOutboundTrainId, plan.recommendedReturnTrainId].includes(item.id));
  const visible = [...selected, ...rows.filter(item => !selected.includes(item))];
  return <Card><CardHeader><CardTitle>火车票完整结果</CardTitle><CardDescription>展示本次全部去程与返程车次。12306 MCP 是社区实现，余票和票价在预订前须到铁路官方核对。</CardDescription></CardHeader><CardContent>{visible.length ? <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>行程</TableHead><TableHead>车次</TableHead><TableHead>车站</TableHead><TableHead>出发 → 抵达</TableHead><TableHead>席别 / 余票</TableHead><TableHead>供应商</TableHead><TableHead>价格</TableHead></TableRow></TableHeader><TableBody>{visible.map(item => <React.Fragment key={`${item.direction}-${item.provider}-${item.id}`}><TableRow><TableCell><div className="flex items-center gap-2"><TrainFront />{item.direction}{selected.includes(item) ? <Badge>推荐</Badge> : null}</div></TableCell><TableCell className="font-medium">{item.trainNumber || '未提供'}</TableCell><TableCell>{item.origin || '未提供'} → {item.destination || '未提供'}</TableCell><TableCell className="whitespace-nowrap">{timeOnly(item.departureAt)} → {timeOnly(item.arrivalAt)}</TableCell><TableCell>{item.seatClass || '未提供'} · {Number.isFinite(item.seatsAvailable) ? `${item.seatsAvailable} 张` : item.seatAvailability || '余票未提供'}</TableCell><TableCell>{item.provider}</TableCell><TableCell>{Number.isFinite(item.totalPrice) ? money(item.totalPrice, item.currency) : '价格未知'}</TableCell></TableRow>{item.trainSegments?.length ? <TableRow><TableCell colSpan={7} className="bg-muted/30"><details><summary className="cursor-pointer text-sm font-medium text-primary">查看逐段车次、席别余票和换乘</summary><div className="mt-3 space-y-3">{item.transfer ? <p className="rounded-md border p-3 text-sm">换乘：{item.transfer.station || '换乘站未提供'} · {item.transfer.sameStation ? '同站换乘' : '需跨站换乘或换乘站未确认'} · 等待 {item.transfer.waitTime || '未提供'}</p> : null}{item.trainSegments.map((segment, index) => <div key={index} className="rounded-md border p-3 text-sm"><strong>{index + 1}. {segment.trainNumber} · {segment.origin} → {segment.destination}</strong><p className="mt-1 text-muted-foreground">{segment.departureAt?.replace('T', ' ').slice(0, 16)} → {segment.arrivalAt?.replace('T', ' ').slice(0, 16)} · 历时 {segment.duration || '未提供'}</p><p className="mt-1">{segment.seatOptions?.map(seat => `${seat.name} ${money(seat.price, 'CNY')} / ${seat.availability}`).join('；') || '席别未提供'}</p>{segment.flags?.length ? <p className="mt-1 text-xs text-muted-foreground">{segment.flags.join(' · ')}</p> : null}</div>)}</div></details></TableCell></TableRow> : null}</React.Fragment>)}</TableBody></Table></div> : <p className="text-sm text-muted-foreground">本次没有可核实的火车票结果。</p>}</CardContent></Card>;
}

export default function PlanView({ plan, selectedDay, memory, actions }) {
  const placeCount = plan.itinerary.reduce((sum, day) => sum + day.stops.length, 0);
  return <div className="flex flex-col gap-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold tracking-[.16em] text-primary">GENERATED ITINERARY</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{plan.originCity || '出发地待定'} → {plan.destination}</h1><p className="mt-2 text-sm text-muted-foreground">{plan.startDate} 起 · {plan.days} 天 · {placeCount} 个地点 · {plan.agentRun?.status === 'completed' ? 'Step Plan 模型完成' : '规则补全'}</p></div><Button variant="outline" onClick={actions.rememberTrip}><BookmarkCheck data-icon="inline-start" />完成后记住这趟旅程</Button></div>
    <FlightResults plan={plan} />
    <TransportTable plan={plan} />
    {(plan.requiredStays?.length || plan.budgetAssessment) ? <Card><CardHeader><CardTitle>行程硬约束与预算</CardTitle><CardDescription>Step 5 从原始需求中整理的约束；预算只核算已取得的交通报价，酒店、餐饮与市内交通尚未计入。</CardDescription></CardHeader><CardContent className="space-y-3 text-sm"><p>旅行时间：{plan.startDate} 至 {plan.endDate} · {plan.days} 天</p>{plan.requiredStays?.map((stay, index) => <p key={index}>必须停留：{stay.city} · {stay.from} 至 {stay.to}</p>)}{plan.budgetAssessment ? <p>总预算 {money(plan.budgetAssessment.totalBudgetCny)} · 已知推荐交通 {money(plan.budgetAssessment.knownTransportCostCny)}（{plan.budgetAssessment.quotedLegs}/2 段有价）· {plan.budgetAssessment.status === 'known_transport_exceeds_budget' ? '仅已知交通已超预算' : `扣除已知交通后剩余 ${money(plan.budgetAssessment.remainingAfterKnownTransportCny)}`}</p> : null}</CardContent></Card> : null}
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="flex min-w-0 flex-col gap-4"><h2 className="text-xl font-semibold">逐日行程</h2>{plan.itinerary.map(day => <Card key={day.day} size="sm"><CardHeader><CardTitle>第 {day.day} 天 · {day.title} {day.requiredStay ? <Badge variant="secondary">必须在 {day.city}</Badge> : null}</CardTitle><CardDescription>{day.date}</CardDescription><CardAction><Button variant="ghost" size="icon-sm" aria-label={`在地图查看第${day.day}天`} onClick={() => actions.setSelectedDay(selectedDay === day.day ? null : day.day)}><MapPinned /></Button></CardAction></CardHeader><CardContent>{day.stops.length ? <div className="flex flex-col gap-3">{day.stops.map(stop => <div key={stop.id} className="grid grid-cols-[48px_1fr] gap-3 border-t pt-3 first:border-t-0 first:pt-0"><span className="font-mono text-xs text-primary">{stop.start || '待核实'}</span><div><p className="font-medium">{stop.name} <Badge variant="secondary" className="ml-2">{stop.category}</Badge></p><p className="mt-1 text-xs text-muted-foreground">{Number.isFinite(stop.duration) ? `游玩约 ${stop.duration} 分钟` : '游玩时长未核实'} · {Number.isFinite(stop.travelMinutes) ? `交通 ${stop.travelMinutes} 分钟` : '交通时间未核实'}{stop.travelSource ? ` · ${stop.travelSource}` : ''}</p></div></div>)}</div> : <p className="text-sm text-muted-foreground">当天尚无可核实的景点；保留这一天的城市与日期安排。</p>}</CardContent></Card>)}</div><div className="flex flex-col gap-4"><Card><CardHeader><CardTitle>路线地图</CardTitle><CardDescription>连线只表示地点顺序，不代表导航路线。</CardDescription></CardHeader><CardContent><TripMap itinerary={plan.itinerary} selectedDay={selectedDay} onSelectDay={actions.setSelectedDay} /></CardContent></Card><Card><CardHeader><CardTitle>住宿</CardTitle><CardDescription>建议区域：{plan.stayArea?.name || '尚未确定'} · 每晚预算 {money(memory.hotelNightBudget)}</CardDescription></CardHeader><CardContent>{plan.hotels?.length ? <div className="flex flex-col gap-2">{plan.hotels.slice(0, 4).map(hotel => <div key={hotel.id} className="flex justify-between gap-3 border-t pt-2 text-sm"><span>{hotel.name}</span><span>{hotel.displayPrice ? money(hotel.displayPrice, hotel.currency) : '价格待核'}</span></div>)}</div> : <p className="text-sm text-muted-foreground">本次未取得酒店报价；区域建议来自行程地点分布。</p>}</CardContent></Card></div></div>
    <div className="grid gap-6 md:grid-cols-2"><Card><CardHeader><CardTitle>景点产品</CardTitle><CardDescription>门票以对应日期和供应商信息为准。</CardDescription></CardHeader><CardContent>{plan.attractionOffers?.length ? plan.attractionOffers.map((offer, index) => <div key={`${offer.placeId}-${index}`} className="border-t py-2 text-sm first:border-t-0">{offer.name} · {offer.productName} <span className="text-muted-foreground">{offer.provider} · {offer.price == null ? '价格未知' : money(offer.price, offer.currency)}</span></div>) : <p className="text-sm text-muted-foreground">本次未取得可核实的景区产品。</p>}</CardContent></Card><Card><CardHeader><CardTitle>餐饮与地面交通</CardTitle><CardDescription>只展示来源明确的餐饮和路线。</CardDescription></CardHeader><CardContent><p className="text-sm">餐饮 {plan.dining?.length || 0} 条 · 核实路线 {plan.groundJourneys?.length || 0} 段</p><p className="mt-2 text-xs text-muted-foreground">转场时间只采用高德实际路线结果；没有路线数据时显示未核实，不做估算。</p></CardContent></Card></div>
  </div>;
}
